name: Release builder for console

on:
  push:
    tags: 'v*'
  workflow_dispatch:
  
env:
  SolutionDirectory: aozora2html/
  ConsolePath: aozora2htmlConsole/aozora2htmlConsole.csproj
  DotnetVersion: 6.0.x
#https://qiita.com/i-tanaka730/items/d46fdfb5c2f601e512c2

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]    
      
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{env.DotnetVersion}}

    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.SolutionDirectory}}
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{env.SolutionDirectory}}

    - name: Test
      run: dotnet test --no-restore --verbosity normal
      working-directory: ${{env.SolutionDirectory}}
  
# Only windows-latest can build Windows, Linux and macOS with ReadyToRun option.
#https://docs.microsoft.com/ja-jp/dotnet/core/deploying/ready-to-run
  publish:
    runs-on: windows-latest
    needs: test
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
        
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{env.DotnetVersion}}
        
    - name: Install dependencies
      run: dotnet restore
      working-directory: ${{env.SolutionDirectory}}

    - name: Publish
      shell: bash
      run: |
        platforms=(
          "win-x64"
          "win-x86"
          "win-arm"
          "win-arm64"
          "linux-x64"
          "linux-musl-x64"
          "linux-arm"
          "linux-arm64"
          "osx-x64"
          "osx.11.0-arm64"
          "osx.10.10-x64"
        )
        for item in "${platforms[@]}" ; do
          dotnet publish ${{env.ConsolePath}} --configuration Release --self-contained true -p:PublishTrimmed=true -p:PublishSingleFile=true --runtime ${item} --output publish/${item}/ -p:PublishReadyToRun=true
        done
        
      working-directory: ${{env.SolutionDirectory}}
      
    - name: Upload to artifact 
      uses: actions/upload-artifact@v2
      if: github.event_name == 'workflow_dispatch'
      with:
        name: Binary
        path: ${{env.SolutionDirectory}}publish
